const pool=require('./database')
const categories=[
    ["accessoryFace", "Vanity"],
    ["alchemy", "Crafting"],
    ["alchemyMaterial", "Crafting"],
    ["armorComponent", "Crafting"],
    ["armorMaterial", "Crafting"],
    ["axe", "Equipment"],
    ["belt", "Equipment"],
    ["blaster", "Equipment"],
    ["bodyLeather", "Equipment"],
    ["bodyMail", "Equipment"],
    ["bodyRobe", "Equipment"],
    ["bow", "Equipment"],
    ["brooch", "Equipment"],
    ["chain", "Equipment"],
    ["charm", "Consumable"],
    ["circle", "Equipment"],
    ["collection", "Cards"],
    ["collection_card", "Cards"],
    ["combat", "Consumable"],
    ["cooking", "Crafting"],
    ["customize_accessory", "Crystals"],
    ["customize_armor", "Crystals"],
    ["customize_weapon", "Crystals"],
    ["dual", "Equipment"],
    ["dyeItem", "Vanity"],
    ["dyeRaw", "Vanity"],
    ["dyeRecipe", "Vanity"],
    ["earring", "Equipment"],
    ["enchantSeal", "Etching"],
    ["enchant_agent", "Material"],
    ["enchant_material", "Material"],
    ["etc", "Crafting"],
    ["extractRecipe", "Vanity"],
    ["fabrication", "Crafting"],
    ["feetLeather", "Equipment"],
    ["feetMail", "Equipment"],
    ["feetRobe", "Equipment"],
    ["fiber", "Crafting"],
    ["gauntlet", "Equipment"],
    ["generalMaterial", "Material"],
    ["glaive", "Equipment"],
    ["handLeather", "Equipment"],
    ["handMail", "Equipment"],
    ["handRobe", "Equipment"],
    ["keyItem", "Crafting"],
    ["lance", "Equipment"],
    ["leather", "Equipment"],
    ["magical", "Vanity"],
    ["metal", "Crafting"],
    ["necklace", "Equipment"],
    ["quest", "Consumable"],
    ["recipe", "Crafting"],
    ["ring", "Equipment"],
    ["rod", "Equipment"],
    ["servant", "Skill Book"],
    ["service", "Account Service"],
    ["shuriken", "Equipment"],
    ["skillbook", "Skill Book"],
    ["staff", "Equipment"],
    ["style_axe", "Vanity"],
    ["style_back", "Vanity"],
    ["style_blaster", "Vanity"],
    ["style_body", "Vanity"],
    ["style_bow", "Vanity"],
    ["style_chain", "Vanity"],
    ["style_circle", "Vanity"],
    ["style_dual", "Vanity"],
    ["style_face", "Vanity"],
    ["style_foot_print", "Vanity"],
    ["style_gauntlet", "Vanity"],
    ["style_glaive", "Vanity"],
    ["style_hair", "Vanity"],
    ["style_lance", "Vanity"],
    ["style_partner", "Vanity"],
    ["style_rod", "Vanity"],
    ["style_shuriken", "Vanity"],
    ["style_staff", "Vanity"],
    ["style_twohand", "Vanity"],
    ["token", "Consumable"],
    ["twohand", "Equipment"],
    ["underwear", "Equipment"],
    ["union", "Crafting"],
    ["weaponMaterial", "Material"]
]
//console.log(categories)

pool.query(`INSERT INTO categories (category, filtered) VALUES ?`, [categories], (err, res)=>{
    if (err) throw err
    else {
        console.log(`Rows added: ${res.affectedRows}`)
        process.exit(0)
    }
})